---
functional:
  - При вводе данных для регистрации пользователь считается зарегистрированным на данном сайте, происходит вход в систему
  - Пользователь должен иметь возможность авторизоваться 
  - Пользователь должен иметь возможность восстановить пароль для авторизации  
  - Пользователь должен иметь возможность игры без авторизации
  - Пользователь должен иметь возможность выбора параметров игры (уровень сложности, тип игры, время для игры, выбор игры по названию и тематике)
  - Пользователь может сдаться в начатой игре 
  - Пользователь может проверить решение 
  - Пользователь может начать матч-реванш
  - Пользователь может писать сообщения в чате игры
  - В игре возможна победа или поражение  
  - Пользователь может настроить область ввода кода 
  - Пользователь может перевести текст задания на английский/русский язык
  - Пользователь может сбросить написанный код  
  - Пользователь может писать код-решение задания
  - Пользователь может выбрать язык программирования
  - Пользователь может просматривать действующие игры других пользователей
  - Пользователь может просматривать профиль других 
  - Пользователь может общаться в чате с другими пользователями 
  - Пользователь может приглашать в игру других пользователей  
  - Пользователь может выполнять действия на панели пользователя (личный профиль, настройки, рейтинг пользователей, "Выход" и др.) 
  - Пользователь может создавать турниры
  - Авторизация сохраняется при обновлении страниц, повторном входе на сайт
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт имеет рейтинг участников 
