functional:
  - требование 1
  - требование 2
non-functional:
  - Разработка с учетом удобства использования
  - Оптимизация для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Удобство при использовании на мобильном устройстве
  - Совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - требование 5
  - требование 6
dfvfdnjdfnj:
  - nghdfg
  - efjehr
neuhf:
YAM
    Проверка входа пользователя с несуществующими логином и паролем
  requirement:
    При неправильном логине или пароле пользователь должен получить сообщение об ошибке
  prerequisites
    Открыта страница логина
  test-data:
    Логин = Логин = hexlet Пароль = badpass
  steps:
    - Вводим логин
    - Вводим пароль
    - Нажимаем кнопку «Войти»
  expected-result: |
    Пользователь должен получить сообщение об ошибке


